language: node_js
node_js:
- '10'
script:
- yarn test
- yarn lint
deploy:
  provider: npm
  email: "$NPM_AUTHOR"
  api_key: "$NPM_TOKEN"
  on:
    branch: master
env:
  global:
  - secure: IuswnT0NYPpe4WJVgZKAtXHFteieMOQm2utK59hoHC+SCSgG+ZHELzRAIvx3bQWZmJSdfHqYDYHlxLnUurQrUPQkwqH8ayqFlNqx+VSa1HQ51yn9oVZmWE6vVeX10iwA6LK/t35VE90Po2m716jMvUr5urEHk3cU0F2+RMGNH7ARuOJ91tfdUr2GQPyD63Qj849LHNHbxCVFoF0MPDBPAAW+hSUW81FbQ2xIm6gChGCCI/AKbtxvx/6u23E7BzgKxSdfdormoLgnthO9CP+AiuS1OaJ3PMsDdu9yqKVrpKhb3mRXs7HfUG9koy7FucbJuBQ4MduvQCi5/mIMOreI5Jejel1CSqIhwO8/PBlrOtHL+qbDZ2koZ3nSEaInDyRmaiciY0MxIkxUS4BncK23P6Bsi3haUyxUGKSbEtSpJ4BVg73Sth4tr4WwSBIysod3Ip3J+UulOpxuaoxVu33jHt+VOd6muAxwQPN7+uxEySPBFc0ZGH59z5Dp9A89n1LwI+JdzqQ1HmpKA286h5tBDGDCXHTHuq0jOEj9RQo7DbIzfjsyQ5Mdg2PiNvavx2Aew/P2saedSyH+ist6/ECIw6Zt7yvMaiF61jfEo+Gby8MRgfYGvE9aNW2nnqVrThWHaM2t/Iu0NuRj4V53BnJcpwS0G5GLJX7z/xg79iDrfMs=
  - secure: I617VgWGJEXe83+0tRTZDbM+jfmcI02OJlnyULZSdeBbxVv8/g1yyDICil1j20Hpo/6eVCOfM9guUWV2KBJgJ7dGwTKIR+zbHK1j3sG+f+rFuEoZ9Mq1+XDFzoIxvKfHHC+ohiS8R2P+0MsMvpSs9lSLKNHUKXk4zk8IrRpD8fRF1XhHi0A9+Wgfx8xTsdHd7nfNOSUmKIfyIJJMHl3BmLoBDWjbT4nInZTDlLK0oYqjCaAg2h35IpeLYqXvXtqeHjU0i9toJOJjJsTPTK4jHER0Wu/MKGwfJjIm3kCyjRssmqAXVh4PuG9Q9+7uWocBeay175z1EFIHxWa7sRbdNfBBV/cqpGpySY/BPaeCm+o5oVoIv6GTDntBwhHZNWOj5MZqmtZfuMKJT68uK4Fe7saTXQyD0djmFp903U1R420IREO+5wKTKDUy3SxeP2ogoqr2sG9LgwgE93+kuZXMYZHkOyhxa5LiafNBw7+7SY9u6S0h9+3AanaS1KAnRPLJHNXz/l2i3QCmaRFbBC8ZAou4c+EjPsjJrx2I9PhH8Ix9CT8mOA6SxEH2Fsh/hBZrHhX5mQ3bflusZZAMMXwyBCW8jG73I0ZrC+0gCyAVGRefieTcsSf1q81Qbn8LJgv5BsWrDVLmBSup71n095lGO7r6WhcNYh87yaW3ftIH30M=
